# Generated by Django 3.1 on 2023-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.JSONField(default=list),
        ),
    ]
